Open_by_bme280
core-rocket/amatsukaze pull request #6
Opened 2019-11-08 01:27 UTC by Yukuro

## 概要
- 高度を使用した頂点検知の検証

## Todo
- [ ] BME280とArduino pro miniを配線する
- [ ] 配線したものを2[s]高度を下げ、2[s]高度を上げ、2[s]高度を下げる
- [ ] 高度を上げたときに``OPENbyBME280_[SUCCESS]``が出ることを確かめる
  - [ ] 出なかったら**なるべく原因を考えて**Request changesする

## Note
- 5回平均のところが自信なさげ

2019-11-09 07:03 UTC, sksat requested changes

2019-11-09 07:03 UTC, sk2sat commented on Avionics/src/main.cpp
> +            average_buff[i] = average_buff[i+1]; //左にずらす
コピー処理は重いので，リングバッファにするべきだと思います．

2019-11-09 07:07 UTC, sk2sat commented on Avionics/src/main.cpp
> +            average = sum / 5.0;
移動平均処理のような他でも使う処理は関数にまとめておいた方が良いです．

2019-11-09 07:29 UTC, sksat requested changes

2019-11-09 07:29 UTC, sk2sat commented on Avionics/src/main.cpp
> +    float average_buff[5] = {0.0};
バッファがこの関数内のローカル変数になっています．static変数かglobal変数にすべきです

2019-11-09 07:36 UTC, sk2sat commented on Avionics/src/main.cpp
> +            average = sum / 5.0;
#8 にて移動平均処理のライブラリを作ってみたので，確認お願いします．

2019-11-11 16:38 UTC, Yukuro commented on Avionics/src/main.cpp
> +    float average_buff[5] = {0.0};
0691e2e にて修正しました

2019-11-11 16:59 UTC, sk2sat commented on Avionics/src/main.cpp
> +    float average_buff[5] = {0.0};
確認しました．しかし，```global::average_buff```という名前だと何のパラメータのためのバッファなのか分かりません．移動平均処理を(同時に)行うパラメータが１つなのであればこれで大丈夫ですが，複数のセンサで移動平均処理を行う場合は良くないです(```average_buff2```のようなものを作ってしまうのはもってのほかです)．
そのため，```global::altitude_average_buf```のようにするか，名前空間を使って```global::altitude::average_buf```のようにすると良いと思います．
後者の場合，センサのクラス(BME)も```global::altitude```に入れておいて，高度に関わるスコープ(ここでは```open_by_BME280```)で```using namespace global::altitude;```とするといちいち```global::altitude::average_buf```などとtypeしなくて済みます．

2019-11-17 06:36 UTC, sksat requested changes

2019-11-17 06:36 UTC, sk2sat commented on Avionics/src/main.cpp
> +        altitude_old = altitude_new;
センサ値を取得する際にdelayが入っていないのでこのループの意味が無くなっています(おそらくそのために #11 の問題が発生しています)．このループ内にdelayを入れるか，センサ値の取得をタイマを用いて行うようにして下さい．
@Yukuro 安全審査書ではこのセンサのサンプリングレートに記載したサンプリングレートはどれくらいですか？

2019-11-17 08:20 UTC, sk2sat commented on Avionics/src/main.cpp
> +        altitude_old = altitude_new;
arduino pro miniだしdelay調整して大体それっぽいサンプリングレートにすればええかな感

2019-11-17 10:39 UTC, sk2sat commented
```.pio/```以下って全部キャッシュだろうしignoreしてええやろと思ったらライブラリを消してしまいましたの顔をしています．

2019-11-17 10:48 UTC, sk2sat commented
platformio.iniで依存ライブラリを指定するようにしました．

2019-11-18 17:09 UTC, Yukuro commented on Avionics/src/main.cpp
> +        altitude_old = altitude_new;
680b12a にて修正しました

2019-11-18 17:10 UTC, merged